### ISSUE TITLE
邮箱号无法识别

### ISSUE THREAD

**Issue by unec2200** [MatchaCabin/gf2gacha#1]

**Comment by unec2200** [comment]
网易yeah邮箱账号开游戏抽卡记录无法用此软件读取记录和uid

**Comment by MatchaCabin** [comment]
`C:\Users\你的用户名\AppData\LocalLow\SunBorn\少女前线2：追放\Player.log`
日志发来看看

**Comment by unec2200** [comment]
> `C:\Users\你的用户名\AppData\LocalLow\SunBorn\少女前线2：追放\Player.log` 日志发来看看

[Uploading Player.log…]()

**Comment by unec2200** [comment]
> `C:\Users\你的用户名\AppData\LocalLow\SunBorn\少女前线2：追放\Player.log` 日志发来看看

[Uploading Player.log…]()

**Comment by unec2200** [comment]
[Uploading Player.log…]()

**Comment by unec2200** [comment]
[Uploading Player.log…]()


> `C:\Users\你的用户名\AppData\LocalLow\SunBorn\少女前线2：追放\Player.log` 日志发来看看

好像上传不了，我发网盘吗

**Comment by unec2200** [comment]
> `C:\Users\你的用户名\AppData\LocalLow\SunBorn\少女前线2：追放\Player.log` 日志发来看看

好像上传不了，我发网盘吗

**Comment by MatchaCabin** [comment]
> > `C:\Users\你的用户名\AppData\LocalLow\SunBorn\少女前线2：追放\Player.log` 日志发来看看
> 
> 好像上传不了，我发网盘吗

都行

**Comment by unec2200** [comment]
> > > `C:\Users\你的用户名\AppData\LocalLow\SunBorn\少女前线2：追放\Player.log` 日志发来看看
> > 
> > 
> > 好像上传不了，我发网盘吗
> 
> 都行

https://pan.baidu.com/s/1efi30N8rLuAfGDvmCo0AYg?pwd=tk3t 
tk3t

**Comment by MatchaCabin** [comment]
看起来和邮箱号没什么关系，应该是你单次游戏里有多次登录行为，导致旧的token失效了
我之前只获取第一条登录记录，可能会获取到失效的token
v1.11.4改为每次都获取最新一条登录记录，你可以试试

**Comment by unec2200** [comment]
> 看起来和邮箱号没什么关系，应该是你单次游戏里有多次登录行为，导致旧的token失效了 我之前只获取第一条登录记录，可能会获取到失效的token v1.11.4改为每次都获取最新一条登录记录，你可以试试

好的谢谢我试试

**Comment by unec2200** [comment]
> 看起来和邮箱号没什么关系，应该是你单次游戏里有多次登录行为，导致旧的token失效了 我之前只获取第一条登录记录，可能会获取到失效的token v1.11.4改为每次都获取最新一条登录记录，你可以试试

忘记回复了，昨天试了试此问题已完美解决
